Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using Postagens.NET.Models;
using Postagens.NET.Services;

namespace Poscategoriaens.NET.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly CategoriaService _service;

        public CategoriasController(CategoriaService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var categorias = await _service.BuscarCategoriasAsync();
            return View(categorias);
        }

        [HttpGet]
        public async Task<JsonResult> ListarCategorias()
        {
            var categorias = await _service.BuscarCategoriasAsync();
            return Json(categorias);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cadastro(Categoria categoria)
        {
            if (categoria.Id > 0)
            {
                await _service.UpdateAsync(categoria);
                return RedirectToAction("Index");

            }
            else
            {
                await _service.InsertAsync(categoria);
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<IActionResult> BuscarUmaCategoria(int id)
        {
            var categoria = await _service.BuscarPorIdAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return Ok(categoria);
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(Categoria categoria)
        {
            if (categoria.Id > 0)
            {
                await _service.DeleteAsync(categoria.Id);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                throw new Exception();
            }

        }
    }
}

Controllers/PublicacoesController.cs
using Microsoft.AspNetCore.Mvc;
using Postagens.NET.Models;
using Postagens.NET.Models.ViewModels;
using Postagens.NET.Services;
using Postagens.NET.Services.Exceptions;
using System.Diagnostics;

namespace Pospubliens.NET.Controllers
{
    public class PublicacoesController : Controller
    {
        private readonly UploadService _uploadService;
        private readonly PublicacaoServices _service;

        public PublicacoesController(UploadService uploadService, PublicacaoServices service)
        {
            _uploadService = uploadService;
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var publicacoes = await _service.ListarPublicacoesAsync();
            return View(publicacoes);
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cadastro(Publicacao publi, List<int> tagIds, IFormFile imagem)
        {
            try
            {
                if (imagem != null && imagem.Length > 0)
                {
                    publi.Imagem = await _uploadService.SaveFileAsync(imagem);
                }
                else if (publi.Id > 0) // Ao editar, mantenha a imagem existente
                {
                    var publicacaoExistente = await _service.BuscarPorIdAsync(publi.Id);
                    publi.Imagem = publicacaoExistente.Imagem; // Mantenha a imagem existente
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Erro ao salvar a imagem: " + ex.Message);
            }

            if (publi.Id > 0)
            {
                await _service.UpdateAsync(publi, tagIds);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                await _service.InsertAsync(publi, tagIds);
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> BuscarPublicacao(int id)
        {
            var publi = await _service.BuscarPorIdAsync(id);
            if (publi == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Publicação não encontrada." });
            }
            return Ok(publi);
        }
        public async Task<IActionResult> Detalhes(int id)
        {
            var publicacao = await _service.VerDetalhes(id);

            if (publicacao == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Publicação não encontrada." });
            }

            return View(publicacao); 
        }
        [HttpPost]
        public async Task<IActionResult> Excluir(int? id)
        {
            try
            {
                // Verifica se o ID foi fornecido
                if (id == null)
                {
                    return RedirectToAction(nameof(Error), new { message = "ID não foi fornecido." });
                }

                // Busca a publicação pelo ID
                var publi = await _service.BuscarPorIdAsync(id.Value);
                if (publi == null)
                {
                    // Redireciona para a página de erro se a publicação não for encontrada
                    return RedirectToAction(nameof(Error), new { message = "Publicação não encontrada." });
                }

                // Exclui a publicação
                await _service.DeleteAsync(publi.Id);
                return RedirectToAction(nameof(Index));
            }
            catch (IntegrityException e)
            {
                // Trata exceções de integridade e redireciona para a página de erro
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }
        }
        public IActionResult Error(string Message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = Message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }
    }
}

Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;
using Postagens.NET.Models;
using Postagens.NET.Services;

namespace Postagens.NET.Controllers
{
    public class TagsController : Controller
    {
        private readonly TagService _service;

        public TagsController(TagService tagService)
        {
            _service = tagService;
        }

        public async Task<IActionResult> Index()
        {
            var tags = await _service.BuscarTagsAsync();
            return View(tags);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Cadastro(Tag tag)
        {
            if (tag.Id > 0)
            {
                await _service.UpdateAsync(tag);
                return RedirectToAction("Index");
            }
            else
            {
                await _service.InsertAsync(tag);
                return RedirectToAction("Index");
            }
            
        }

        [HttpGet]
        public async Task<JsonResult> BuscarTags()
        {
            var tags = await _service.BuscarTagsAsync();
            return Json(tags);
        }

        [HttpGet]
        public async Task <IActionResult> BuscarPorId(int id)
        {
            var tag =  await _service.BuscarPorIdAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return Ok(tag);
        }
        
        [HttpPost]
        public async Task <IActionResult> Excluir(Tag tag)
        {
            if(tag.Id > 0)
            {
             await _service.DeleteAsync(tag.Id);
             return RedirectToAction(nameof(Index));
            }
            else
            {
                throw new Exception();
            }

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br" ng-app="myApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Postagens.NET</title>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>
    <script src="~/app/app.js"></script>
    <script src="~/js/controllers/tagctrll.js"></script>
    <script src="~/js/controllers/publicacaoctrll.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cerulean.css" />
    <script src="~/js/controllers/categoriactrll.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Postagens.NET.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-primary navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Postagens.NET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publicacoes" asp-action="Index">Publicações</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Postagens.NET - Desenvolvido por Leonardo Oliveira
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>